project:
  type: website
  output-dir: docs
  preview: 
    port: 1111
execute:
  freeze: auto  # re-render only when source changes
website:
  site-url: https://datasciencecampus.github.io/coding-in-the-open/
  repo-url: https://github.com/datasciencecampus/coding-in-the-open
  repo-actions: issue
  search: false
  title: Coding in the Open
  favicon: /assets/favicon.ico
  page-navigation: true
  margin-header: |
    <a href="https://datasciencecampus.ons.gov.uk/">
      <img src="https://datasciencecampus.ons.gov.uk/wp-content/uploads/sites/10/2017/03/data-science-campus-logo-new.svg" alt="Data Science Campus logo">
    </a>
  twitter-card: 
    site: https://twitter.com/DataSciCampus
  sidebar:
    style: floating
    title: Coding in the Open
    contents:
      - index.qmd
      - section: Guidance
        contents:
        - ./general-considerations/guidance.qmd
        - ./open-at-the-start/guidance.qmd
        - ./open-at-the-end/guidance.qmd
        - ./never-open/index.qmd
        - ./what-could-go-wrong/checklist.qmd
      - ./general-considerations/references.qmd
    footer: |
      :::{.callout-important}
      These pages are still in active development, and at this stage do not represent a completed or agreed set of guidance.
      :::
    collapse-level: 2
    tools:
      - icon: twitter
        href: https://twitter.com/DataSciCampus
      - icon: github
        href: https://github.com/datasciencecampus
      - icon: globe
        href: https://datasciencecampus.ons.gov.uk/
  page-footer: 
    center: |
      ![Open Government License logo](/assets/images/ogl.png) All content is available under the [Open Government Licence V3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/), except where otherwise stated.
      <br>Built using [quarto](https://quarto.org/). All sources are acknowledged in the [references](/general-considerations/references.qmd) page. Updated on {{< var update-date >}}.

format:
  html:
    theme: 
      light: default
      dark: darkly
    css: /assets/styles.css
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: "On this page"
    toc-location: right

bibliography: ./bibliography/references.bib
biblio-title: ""
csl: ./bibliography/ieee.csl
