project:
  type: website
  output-dir: docs
  preview: 
    port: 1111

execute:
  freeze: auto  # re-render only when source changes

website:
  site-url: https://datasciencecampus.github.io/coding-in-the-open/
  repo-url: https://github.com/datasciencecampus/coding-in-the-open
  repo-actions: issue
  title: Coding in the Open
  favicon: /assets/favicon.ico
  page-navigation: true
  twitter-card: 
    site: https://twitter.com/DataSciCampus
  sidebar:
    style: floating
    title: Coding in the Open
    logo: https://datasciencecampus.ons.gov.uk/wp-content/uploads/sites/10/2017/03/data-science-campus-logo-new.svg
    logo-href: https://datasciencecampus.ons.gov.uk/
    logo-alt: Data Science Campus logo
    contents:
      - index.qmd
      - section: Guidance
        contents:
        - ./common/general_considerations.qmd
        - ./private_to_public/guidance.qmd
      - ./common/references.qmd
    footer: |
      :::{.callout-important}
      These pages are still in active development, and at this stage do not represent a completed or agreed set of guidance.
      :::
    collapse-level: 2
    tools:
      - icon: twitter
        href: https://twitter.com/DataSciCampus
      - icon: github
        href: https://github.com/datasciencecampus
      - icon: globe
        href: https://datasciencecampus.ons.gov.uk/
  page-footer: 
    center: |
      ![Logo image](/assets/images/ogl.png) All content is available under the [Open Government Licence V3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/), except where otherwise stated.
      <br>Built using [quarto](https://quarto.org/). Are sources are aknowledged in the [references](/common/references.qmd) page. Updated on {{< var update-date >}}.

format:
  html:
    theme: 
      light: default
      dark: darkly
    css: /assets/styles.css
    toc: true
    toc-depth: 3
    toc-expand: 3
    toc-title: "On this page"
    toc-location: right

bibliography: ./bibliography/references.bib
biblio-title: ""
csl: ./bibliography/ieee.csl
