name: Render and Publish
on:
  push:
    branches:
      - main  
      - gh-pages

jobs:
  build-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v3
          
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          with:
            # To install LaTeX to build PDF book 
            # tinytex: true 
            # uncomment below and fill to pin a version
            version: 1.3.340
        
        - name: Render Book project # to render to HTML only, default includes pdf
          uses: quarto-dev/quarto-actions/render@v2
          with:
            to: html
          
        - name: Publish HTML book
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages
            path: docs
            render: false
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
        